export type ElementCategory =
  | 'layout'
  | 'container'
  | 'text'
  | 'heading'
  | 'media'
  | 'interactive'
  | 'form'
  | 'list'
  | 'table'
  | 'custom';

export interface HTMLTagMetadata {
  tag: string;
  category: ElementCategory;
  defaultDisplay: string;
  isReplacedElement: boolean;      // e.g. img, video, iframe, input (cannot have pseudo elements)
  supportsChildren: boolean;       // e.g. false for img, hr, br, input
  supportsInlineDimensions: boolean; // false for purely inline elements unless display modified
  inheritsTextStyles: boolean;
  defaultAccessibilityRole?: string;
}

export const ELEMENT_CLASSIFICATIONS: Record<string, HTMLTagMetadata> = {
  div: {
    tag: 'div',
    category: 'container',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
  },
  section: {
    tag: 'section',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'region',
  },
  article: {
    tag: 'article',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'article',
  },
  header: {
    tag: 'header',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'banner',
  },
  footer: {
    tag: 'footer',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'contentinfo',
  },
  nav: {
    tag: 'nav',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'navigation',
  },
  main: {
    tag: 'main',
    category: 'layout',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'main',
  },
  span: {
    tag: 'span',
    category: 'text',
    defaultDisplay: 'inline',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: false,
    inheritsTextStyles: true,
  },
  p: {
    tag: 'p',
    category: 'text',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'paragraph',
  },
  h1: {
    tag: 'h1',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  h2: {
    tag: 'h2',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  h3: {
    tag: 'h3',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  h4: {
    tag: 'h4',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  h5: {
    tag: 'h5',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  h6: {
    tag: 'h6',
    category: 'heading',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'heading',
  },
  a: {
    tag: 'a',
    category: 'interactive',
    defaultDisplay: 'inline',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: false,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'link',
  },
  button: {
    tag: 'button',
    category: 'interactive',
    defaultDisplay: 'inline-block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'button',
  },
  img: {
    tag: 'img',
    category: 'media',
    defaultDisplay: 'inline-block',
    isReplacedElement: true,
    supportsChildren: false,
    supportsInlineDimensions: true,
    inheritsTextStyles: false,
    defaultAccessibilityRole: 'img',
  },
  video: {
    tag: 'video',
    category: 'media',
    defaultDisplay: 'inline-block',
    isReplacedElement: true,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: false,
  },
  input: {
    tag: 'input',
    category: 'form',
    defaultDisplay: 'inline-block',
    isReplacedElement: true,
    supportsChildren: false,
    supportsInlineDimensions: true,
    inheritsTextStyles: false,
  },
  textarea: {
    tag: 'textarea',
    category: 'form',
    defaultDisplay: 'inline-block',
    isReplacedElement: true,
    supportsChildren: false,
    supportsInlineDimensions: true,
    inheritsTextStyles: false,
  },
  select: {
    tag: 'select',
    category: 'form',
    defaultDisplay: 'inline-block',
    isReplacedElement: true,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: false,
  },
  ul: {
    tag: 'ul',
    category: 'list',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'list',
  },
  ol: {
    tag: 'ol',
    category: 'list',
    defaultDisplay: 'block',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'list',
  },
  li: {
    tag: 'li',
    category: 'list',
    defaultDisplay: 'list-item',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'listitem',
  },
  table: {
    tag: 'table',
    category: 'table',
    defaultDisplay: 'table',
    isReplacedElement: false,
    supportsChildren: true,
    supportsInlineDimensions: true,
    inheritsTextStyles: true,
    defaultAccessibilityRole: 'table',
  },
};
