FROM node:20-alpine AS base
RUN npm install -g pnpm turbo

WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @nirmaanify/database generate
RUN pnpm --filter api build

EXPOSE 4000
CMD ["pnpm", "--filter", "api", "start"]
