import { CSSPropertyDefinition } from '../../types/property';

export const width: CSSPropertyDefinition = {
  name: 'width',
  label: 'Width',
  category: 'box-model',
  description: 'Sets an element’s width.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['auto', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp', 'min', 'max'],
  defaultValue: 'auto',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const minWidth: CSSPropertyDefinition = {
  name: 'min-width',
  label: 'Min Width',
  category: 'box-model',
  description: 'Sets the minimum width of an element.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['auto', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp'],
  defaultValue: 'auto',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const maxWidth: CSSPropertyDefinition = {
  name: 'max-width',
  label: 'Max Width',
  category: 'box-model',
  description: 'Sets the maximum width of an element.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['none', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp'],
  defaultValue: 'none',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const height: CSSPropertyDefinition = {
  name: 'height',
  label: 'Height',
  category: 'box-model',
  description: 'Sets an element’s height.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['auto', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp', 'min', 'max'],
  defaultValue: 'auto',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const minHeight: CSSPropertyDefinition = {
  name: 'min-height',
  label: 'Min Height',
  category: 'box-model',
  description: 'Sets the minimum height of an element.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['auto', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp'],
  defaultValue: 'auto',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const maxHeight: CSSPropertyDefinition = {
  name: 'max-height',
  label: 'Max Height',
  category: 'box-model',
  description: 'Sets the maximum height of an element.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['none', 'max-content', 'min-content', 'fit-content'],
  supportedFunctions: ['calc', 'var', 'clamp'],
  defaultValue: 'none',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const margin: CSSPropertyDefinition = {
  name: 'margin',
  label: 'Margin',
  category: 'box-model',
  description: 'Sets the margin area on all four sides of an element.',
  valueType: ['length', 'percentage', 'keyword'],
  validKeywords: ['auto'],
  supportedFunctions: ['calc', 'var'],
  defaultValue: '0px',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const padding: CSSPropertyDefinition = {
  name: 'padding',
  label: 'Padding',
  category: 'box-model',
  description: 'Sets the padding area on all four sides of an element.',
  valueType: ['length', 'percentage'],
  supportedFunctions: ['calc', 'var'],
  defaultValue: '0px',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const aspectRatio: CSSPropertyDefinition = {
  name: 'aspect-ratio',
  label: 'Aspect Ratio',
  category: 'box-model',
  description: 'Sets a preferred aspect ratio for the box.',
  valueType: ['keyword', 'string'],
  validKeywords: ['auto', '1 / 1', '4 / 3', '16 / 9', '21 / 9', '9 / 16', '3 / 2'],
  defaultValue: 'auto',
  inherited: false,
  animatable: true,
  responsive: true,
  supportsVariables: true,
  supportsGlobalValues: true,
  browserSupport: { baseline: 'widely' },
};

export const boxModelProperties = [
  width,
  minWidth,
  maxWidth,
  height,
  minHeight,
  maxHeight,
  margin,
  padding,
  aspectRatio,
];
