export const ROUTES = {
  HOME: '/',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
  },
  DASHBOARD: {
    OVERVIEW: '/',
    PROJECTS: '/projects',
    PROJECT_DETAIL: (projectId: string) => `/projects/${projectId}`,
    PROJECT_STUDIO: (projectId: string) => `/projects/${projectId}/studio`,
    PROJECT_CMS: (projectId: string) => `/projects/${projectId}/cms`,
    PROJECT_BACKEND: (projectId: string) => `/projects/${projectId}/backend`,
    PROJECT_DATABASE: (projectId: string) => `/projects/${projectId}/database`,
    PROJECT_PLUGINS: (projectId: string) => `/projects/${projectId}/plugins`,
    PROJECT_DEPLOY: (projectId: string) => `/projects/${projectId}/deployment`,
    PROJECT_SETTINGS: (projectId: string) => `/projects/${projectId}/settings`,
    CMS: '/cms',
    BACKEND: '/backend',
    DATABASE: '/database-builder',
    PLUGINS: '/plugins',
    DEPLOY: '/deploy',
    TEAM: '/team',
    STORAGE: '/storage',
    LAUNCH: '/launch',
    GOVERNANCE: '/governance',
  },
} as const;
